### PR TITLE
SavantBuffer DbConnector

### PR DESCRIPTION
**Pull request by treborgero**
Added DbConnector per Reddit discussion.

https://www.reddit.com/r/dotnetcore/comments/gb0goc/net_dbconnector_v112_released/fp37aju/?utm_source=share&utm_medium=web2x

### CODE REVIEW

**Comment by Grauenwolf** [comment]
The PostgreSQL tests under MultipleDBTests are failing. It seems that the GetByKey is failing for PostgreSQL, but I don't see why.

All other tests are passing.

**Comment by Grauenwolf** [comment]
There was also a mistake in the markdown file, but I fixed that.

**Comment by treborgero** [comment]
> 
> 
> The PostgreSQL tests under MultipleDBTests are failing. It seems that the GetByKey is failing for PostgreSQL, but I don't see why.
> 
> All other tests are passing.

Yes, It's failing for me for the other projects as well. Can you please confirm? It might be a schema issue.

**Comment by treborgero** [comment]
> 
> 
> There was also a mistake in the markdown file, but I fixed that.

Thank you.

**Comment by Grauenwolf** [comment]
This is what I'm seeing:

image

As you can see, not all of the tests are failing for DBConnector, just the ones that use GetByKey.

**Comment by Grauenwolf** [comment]
There was a bug in the PostgreSqlDb project that was preventing it from resetting the database. But that seems to be unrelated.

**Comment by treborgero** [comment]
> 
> 
> There was a bug in the PostgreSqlDb project that was preventing it from resetting the database. But that seems to be unrelated.

Got it, sorry for that. I found the issue and it's due to "case-sensitivity". It's amazing no one has never reported this (including myself). It seems I forgot to make the columns match in a "case-insensitive" way just like all databases normally do 😅

I'll make the fix, re-publish the library, and then make the updates to your project.

**Pull request merged**
