### PR TITLE
ORM Cookbook Updates (TryCRUD, Immutable, Test Suites, Model Organizations)

### PR DESCRIPTION
**Pull request by mikependon**
It contains a lot of updates due to the fact that I had organized the models into single folder. I could not run my Setup.cs for now on my DEV machine. Will revisit it later.

https://github.com/Grauenwolf/DotNet-ORM-Cookbook/issues/71
https://github.com/Grauenwolf/DotNet-ORM-Cookbook/issues/70
https://github.com/Grauenwolf/DotNet-ORM-Cookbook/issues/69
https://github.com/Grauenwolf/DotNet-ORM-Cookbook/issues/68
https://github.com/Grauenwolf/DotNet-ORM-Cookbook/issues/67
https://github.com/Grauenwolf/DotNet-ORM-Cookbook/issues/20

### CODE REVIEW

**Comment by Grauenwolf** [comment]
When you move .cs files, you may have to update the .md files to reflect the new locations.

For example, I have to change this line in `SingleModelCrud.md`

    @snippet cs [../Recipes.RepoDb\Entities\EmployeeClassificationSingleModelCrud.cs] EmployeeClassificationSingleModelCrud

In case you were unaware, the `@snippet` is what allows us to embed source code directly into the markdown files without having to manually keep them in sync.

**Comment by Grauenwolf** [comment]
I was able to fix some of the tests, but the ImmutableTests and SingleModelCrudAsync tests are failing and I don't know why.

**Comment by mikependon** [comment]
> When you move .cs files, you may have to update the .md files to reflect the new locations.

I wasn't aware TBH, until earlier before I commit I found some conflicting files with regards to these. I had never pushed it as I do not have time. Will check for it.

> I was able to fix some of the tests, but the ImmutableTests and SingleModelCrudAsync tests are failing and I don't know why.

I will look at it now.

**Comment by mikependon** [comment]
I used to have these additional conflicts. Do not know why! I will investigate.

image

**Comment by mikependon** [comment]
I found out that on the `Recipes.RepoDb.SingleModelCrudAsync`, the calls to *UpdateAsync* is recurring. So I fixed this!

For the *Immutable*, RepoDb does not support it actually. I have to somehow download the data from the DB as a mutable then set manually the result as immutable.

**Comment by Grauenwolf** [comment]
You can ignore conflicts in the .htm files. They are regenerated from the .md files when the project is built.

**Comment by Grauenwolf** [comment]
>  I have to somehow download the data from the DB as a mutable then set manually the result as immutable.

That's essentially what I do for NHibernate.

**Comment by mikependon** [comment]
It is now working on my machine, I am updating the MD files now.

**Comment by Grauenwolf** [comment]
Confirmed all tests passing.

**Pull request merged**
