### PR TITLE
EF Core query filter.

### PR DESCRIPTION
**Pull request by Arnab-Developer**
I have created an example for EF Core's query filter.

### CODE REVIEW

**Comment by Grauenwolf** [comment]
Overall I like it. I did tweak some things regarding the testing strategy and presentation. If you have any concerns let me know. 

If you didn't create the helpers, you need to update them with the appropriate license/copyright information. (And if you did create them, feel free to put your name on those files if you want.)

Once you say its ready, I'll commit the merge and regenerate the website.

**Comment by Arnab-Developer** [comment]
I don't have any concerns for your changes. Looks good.

I have added the copyright information for the helpers.

**Comment by Grauenwolf** [comment]
I have to ask him for permission because there's no license on that page. But I'm sure he'll say yes.

Thank you for your work on this.

**Comment by Grauenwolf** [comment]
It should be live shortly. Thank you for your help.

**Comment by Arnab-Developer** [comment]
Thanks.

**Pull request merged**
